export const products = [
    {
      product_id: 1,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Shirt",
      ss_cat_name: "Shirt",
      rating: 4.6,
      price: 599,
      image_link_images: "https://assets.ajio.com/medias/sys_master/root/20231205/G3z0/656ed440ddf7791519b1e6e2/-473Wx593H-461119105-blue-MODEL.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Blue",
      print_pattern: "Check",
      major_category: "Top",
    },
    {
      product_id: 2,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Jacket",
      ss_cat_name: "Jacket",
      rating: 4.8,
      price: 999,
      image_link_images: "https://m.media-amazon.com/images/I/61ERl8U2SRL._AC_UY1100_.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Black",
      print_pattern: "Plain",
      major_category: "Top",
    },
    {
      product_id: 3,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Shirt",
      ss_cat_name: "Shirt",
      rating: 4.6,
      price: 599,
      image_link_images: "https://assets.ajio.com/medias/sys_master/root/20231205/G3z0/656ed440ddf7791519b1e6e2/-473Wx593H-461119105-blue-MODEL.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Blue",
      print_pattern: "Check",
      major_category: "Top",
    },
    {
      product_id: 4,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Jacket",
      ss_cat_name: "Jacket",
      rating: 4.8,
      price: 999,
      image_link_images: "https://m.media-amazon.com/images/I/61ERl8U2SRL._AC_UY1100_.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Black",
      print_pattern: "Plain",
      major_category: "Top",
    },
    {
      product_id: 5,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Shirt",
      ss_cat_name: "Shirt",
      rating: 4.6,
      price: 599,
      image_link_images: "https://assets.ajio.com/medias/sys_master/root/20231205/G3z0/656ed440ddf7791519b1e6e2/-473Wx593H-461119105-blue-MODEL.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Blue",
      print_pattern: "Check",
      major_category: "Top",
    },
    {
      product_id: 6,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Jacket",
      ss_cat_name: "Jacket",
      rating: 4.8,
      price: 999,
      image_link_images: "https://m.media-amazon.com/images/I/61ERl8U2SRL._AC_UY1100_.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Black",
      print_pattern: "Plain",
      major_category: "Top",
    },
    {
      product_id: 7,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Shirt",
      ss_cat_name: "Shirt",
      rating: 4.6,
      price: 599,
      image_link_images: "https://assets.ajio.com/medias/sys_master/root/20231205/G3z0/656ed440ddf7791519b1e6e2/-473Wx593H-461119105-blue-MODEL.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Blue",
      print_pattern: "Check",
      major_category: "Top",
    },
    {
      product_id: 8,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Jacket",
      ss_cat_name: "Jacket",
      rating: 4.8,
      price: 999,
      image_link_images: "https://m.media-amazon.com/images/I/61ERl8U2SRL._AC_UY1100_.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Black",
      print_pattern: "Plain",
      major_category: "Top",
    },
    {
      product_id: 9,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Shirt",
      ss_cat_name: "Shirt",
      rating: 4.6,
      price: 599,
      image_link_images: "https://assets.ajio.com/medias/sys_master/root/20231205/G3z0/656ed440ddf7791519b1e6e2/-473Wx593H-461119105-blue-MODEL.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Blue",
      print_pattern: "Check",
      major_category: "Top",
    },
    {
      product_id: 10,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Jacket",
      ss_cat_name: "Jacket",
      rating: 4.8,
      price: 999,
      image_link_images: "https://m.media-amazon.com/images/I/61ERl8U2SRL._AC_UY1100_.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Black",
      print_pattern: "Plain",
      major_category: "Top",
    },
    {
      product_id: 11,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Shirt",
      ss_cat_name: "Shirt",
      rating: 4.6,
      price: 599,
      image_link_images: "https://assets.ajio.com/medias/sys_master/root/20231205/G3z0/656ed440ddf7791519b1e6e2/-473Wx593H-461119105-blue-MODEL.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Blue",
      print_pattern: "Check",
      major_category: "Top",
    },
    {
      product_id: 12,
      portfolio: "Top",
      category: "Men",
      s_cat: "Men Jacket",
      ss_cat_name: "Jacket",
      rating: 4.8,
      price: 999,
      image_link_images: "https://m.media-amazon.com/images/I/61ERl8U2SRL._AC_UY1100_.jpg",
      fabric: "Cotton",
      order_count: 1200,
      color: "Black",
      print_pattern: "Plain",
      major_category: "Top",
    },
  ];